// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// b2d
double b2d(NumericVector x);
RcppExport SEXP _rgraph6_b2d(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(b2d(x));
    return rcpp_result_gen;
END_RCPP
}
// d2b
std::vector<double> d2b(unsigned long int x);
RcppExport SEXP _rgraph6_d2b(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned long int >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(d2b(x));
    return rcpp_result_gen;
END_RCPP
}
// decodeElist
IntegerVector decodeElist(IntegerVector x, IntegerVector b);
RcppExport SEXP _rgraph6_decodeElist(SEXP xSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(decodeElist(x, b));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rgraph6_b2d", (DL_FUNC) &_rgraph6_b2d, 1},
    {"_rgraph6_d2b", (DL_FUNC) &_rgraph6_d2b, 1},
    {"_rgraph6_decodeElist", (DL_FUNC) &_rgraph6_decodeElist, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_rgraph6(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
