# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

b2d <- function(x) {
    .Call('_rgraph6_b2d', PACKAGE = 'rgraph6', x)
}

d2b <- function(x) {
    .Call('_rgraph6_d2b', PACKAGE = 'rgraph6', x)
}

decodeElist <- function(x, b) {
    .Call('_rgraph6_decodeElist', PACKAGE = 'rgraph6', x, b)
}

